version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/var/www/
      - /home/app/crm-tirone:/var/www/html
      - /home/app/crm-tirone/storage:/var/www/html/storage
      - /home/app/crm-tirone/public/build:/var/www/siriusalpha.com.br/public/build
    ports:
      - "82:80"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: mysql:8.0.33
    container_name: db_crm
    restart: unless-stopped
    tty: true
    ports:
      - "3334:3306"
    environment:
      MYSQL_DATABASE: crm_local
      MYSQL_ROOT_PASSWORD: tirone@2020
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_PASSWORD: dev@2020
      MYSQL_USER: crmti
    volumes:
      - /home/app/crm-tirone/db_data:/var/lib/mysql
      - ./:/var/www/
      - ./mysql:/etc/mysql/my.cnf
    networks:
      - app_network

networks:
  app_network:
